"""
path_planner.py
===============
A* path planner on the occupancy grid map generated by extract_ground_truth.py.

Coordinate conventions (must match extract_ground_truth.py exactly):
  - col = (world_x - world_min_x) / resolution          # increases East
  - row = (world_max_y - world_y) / resolution           # increases South (Y flipped)

So in pixel space: row 0 = top of image = maximum world Y (North).
                   col 0 = left of image = minimum world X (West).

Usage (inside Webots controller):
    planner = PathPlanner("sim_logs/map_estimate.png", "sim_logs/map_metadata.json")
    waypoints = planner.plan(-0.375, 0.375, 3.386, -3.042)
    # waypoints → [(x0,y0), (x1,y1), ..., (goal_x, goal_y)]

Standalone test (outside Webots — saves a debug PNG):
    python path_planner.py
"""

import json
import math
import heapq
import os
import numpy as np
from PIL import Image


# ── Robot physical constant ──────────────────────────────────────────────────
ROBOT_RADIUS = 0.25   # metres — used to inflate obstacles so robot doesn't clip walls


class PathPlanner:
    """A* planner operating on a pre-built binary occupancy grid with clearance cost."""

    def __init__(self, map_png_path: str, metadata_path: str):
        """
        Args:
            map_png_path  : Path to map_estimate.png (black walls, white free)
            metadata_path : Path to map_metadata.json (coordinate transform)
        """
        # ── Load coordinate transform ─────────────────────────────────────
        with open(metadata_path) as f:
            meta = json.load(f)

        self._world_min_x = meta["world_min_x"]
        self._world_max_y = meta["world_max_y"]
        self._res         = meta["resolution"]     # metres per pixel
        self._width       = meta["width"]
        self._height      = meta["height"]
        # OriginMarker position in absolute world coords.
        # All (x, y) inputs to plan() are origin-relative;
        # we add this offset before converting to pixels.
        self._origin_x    = meta["origin_x"]
        self._origin_y    = meta["origin_y"]

        # ── Load map → binary occupancy grid ─────────────────────────────
        img = Image.open(map_png_path).convert("L")   # grayscale
        arr = np.array(img, dtype=np.uint8)

        # Pixels darker than 128 are walls
        self._raw_grid = arr < 128    # True = occupied

        # ── Inflate obstacles by robot radius ────────────────────────────
        self._inflation_px = int(math.ceil(ROBOT_RADIUS / self._res))
        self._grid = self._inflate(self._raw_grid, self._inflation_px)

        print(f"[PathPlanner] Map: {self._width}×{self._height}px, "
              f"res={self._res}m/px, inflation={self._inflation_px}px")
        print(f"[PathPlanner] World bounds: "
              f"x=[{self._world_min_x:.2f}, {self._world_min_x + self._width*self._res:.2f}] "
              f"y=[{self._world_max_y - self._height*self._res:.2f}, {self._world_max_y:.2f}]")

    # ── Public API ───────────────────────────────────────────────────────────

    def plan(
        self,
        start_x: float, start_y: float,
        goal_x:  float, goal_y:  float,
    ) -> list[tuple[float, float]] | None:
        """
        Compute an obstacle-free path from (start_x, start_y) to (goal_x, goal_y)
        in origin-relative world coordinates.

        Returns:
            List of (x, y) waypoints ending at the goal, or None if unreachable.
            The start position is NOT included — only the path ahead.
        """
        start_px = self._world_to_pixel(start_x, start_y)
        goal_px  = self._world_to_pixel(goal_x,  goal_y)

        # Clamp to map bounds
        start_px = self._clamp_to_free(start_px)
        goal_px  = self._clamp_to_free(goal_px)

        if start_px is None or goal_px is None:
            print("[PathPlanner] ERROR: start or goal is completely inside an obstacle.")
            return None

        # Run A*
        pixel_path = self._astar(start_px, goal_px)
        if pixel_path is None:
            print(f"[PathPlanner] No path found from {start_px} to {goal_px}")
            return None

        # Smooth: remove redundant waypoints using line-of-sight checks
        pixel_path = self._smooth(pixel_path)

        # Convert back to world coordinates
        waypoints = [self._pixel_to_world(col, row) for row, col in pixel_path]

        # Always make the final waypoint exactly the requested goal
        waypoints[-1] = (goal_x, goal_y)

        print(f"[PathPlanner] Path: ({start_x:.2f},{start_y:.2f}) → "
              f"({goal_x:.2f},{goal_y:.2f}), {len(waypoints)} waypoints")
        return waypoints

    def replan_on_grid(
        self,
        live_grid: np.ndarray,
        start_x: float, start_y: float,
        goal_x:  float, goal_y:  float,
        goal_clearance_px: int = 15,
        start_clearance_px: int = 5,
    ) -> list[tuple[float, float]] | None:
        """
        Replan path using an external/live occupancy grid (e.g. from LiveMap).

        Clears clearance circles around both start (robot position) and goal (victim)
        so inflation does not falsely trap either endpoint.
        """
        # Work on a copy so we don't corrupt the cached live grid
        grid = live_grid.copy()

        # Force the area around the goal to be free (victims are in open space)
        gr, gc = self._world_to_pixel(goal_x, goal_y)
        r = goal_clearance_px
        for dr in range(-r, r + 1):
            for dc in range(-r, r + 1):
                if dr * dr + dc * dc <= r * r:
                    nr, nc = gr + dr, gc + dc
                    if 0 <= nr < self._height and 0 <= nc < self._width:
                        grid[nr, nc] = False

        # Force the area around the robot start to be free
        sr_px, sc_px = self._world_to_pixel(start_x, start_y)
        r_s = start_clearance_px
        for dr in range(-r_s, r_s + 1):
            for dc in range(-r_s, r_s + 1):
                if dr * dr + dc * dc <= r_s * r_s:
                    nr, nc = sr_px + dr, sc_px + dc
                    if 0 <= nr < self._height and 0 <= nc < self._width:
                        grid[nr, nc] = False

        saved_grid = self._grid
        try:
            self._grid = grid
            return self.plan(start_x, start_y, goal_x, goal_y)
        finally:
            self._grid = saved_grid

    def is_path_blocked(
        self,
        live_grid: np.ndarray,
        start_x: float, start_y: float,
        waypoints: list[tuple[float, float]],
        check_segments: int = 2,
    ) -> bool:
        """
        Check if the path from (start_x, start_y) through upcoming waypoints
        intersects any occupied cell on the live grid.

        Args:
            live_grid       : Inflated combined occupancy grid.
            start_x, start_y: Current robot position (origin-relative).
            waypoints       : Active list of waypoints ahead.
            check_segments  : Number of waypoint segments ahead to verify.

        Returns:
            True if an obstacle intersects the path ahead, False otherwise.
        """
        if not waypoints:
            return False

        points_to_check = [(start_x, start_y)] + list(waypoints[:check_segments])

        for i in range(len(points_to_check) - 1):
            p0 = points_to_check[i]
            p1 = points_to_check[i + 1]

            r0, c0 = self._world_to_pixel(p0[0], p0[1])
            r1, c1 = self._world_to_pixel(p1[0], p1[1])

            dr = abs(r1 - r0)
            dc = abs(c1 - c0)
            sr = 1 if r1 > r0 else -1
            sc = 1 if c1 > c0 else -1
            err = dr - dc

            curr_r, curr_c = r0, c0
            step_count = 0
            while True:
                # Skip first 3 pixels if starting from robot pos to avoid self-inflation
                if i > 0 or step_count > 3:
                    if 0 <= curr_r < self._height and 0 <= curr_c < self._width:
                        if live_grid[curr_r, curr_c]:
                            return True

                if curr_r == r1 and curr_c == c1:
                    break

                e2 = 2 * err
                if e2 > -dc:
                    err -= dc
                    curr_r += sr
                if e2 < dr:
                    err += dr
                    curr_c += sc
                step_count += 1

        return False

    # ── Coordinate transforms ────────────────────────────────────────────────

    def _world_to_pixel(self, ox: float, oy: float) -> tuple[int, int]:
        """Origin-relative (x,y) → pixel (row, col)."""
        # Convert origin-relative → absolute world coords
        wx = ox + self._origin_x
        wy = oy + self._origin_y
        col = int((wx - self._world_min_x) / self._res)
        row = int((self._world_max_y - wy)  / self._res)
        col = max(0, min(self._width  - 1, col))
        row = max(0, min(self._height - 1, row))
        return (row, col)

    def _pixel_to_world(self, col: int, row: int) -> tuple[float, float]:
        """Pixel (row, col) → origin-relative world (x, y)."""
        wx = self._world_min_x + (col + 0.5) * self._res
        wy = self._world_max_y - (row + 0.5) * self._res
        # Convert absolute world → origin-relative
        ox = wx - self._origin_x
        oy = wy - self._origin_y
        return (ox, oy)

    # ── Obstacle inflation ────────────────────────────────────────────────────

    @staticmethod
    def _inflate(grid: np.ndarray, radius_px: int) -> np.ndarray:
        """
        Expand every occupied cell by radius_px pixels (circular kernel).
        Pure numpy — no scipy dependency.
        """
        if radius_px <= 0:
            return grid.copy()

        # Build circular structuring element
        d = 2 * radius_px + 1
        y, x = np.ogrid[-radius_px:radius_px + 1, -radius_px:radius_px + 1]
        kernel = (x * x + y * y <= radius_px * radius_px).astype(np.uint8)

        # 2D max-filter via manual sliding window using numpy stride tricks
        # (equivalent to binary dilation but without scipy)
        from numpy.lib.stride_tricks import sliding_window_view
        h, w = grid.shape
        padded = np.pad(grid.astype(np.uint8), radius_px, mode='edge')
        windows = sliding_window_view(padded, (d, d))   # shape: (h, w, d, d)
        inflated = (windows * kernel).max(axis=(2, 3)) > 0
        return inflated

    # ── A* search ────────────────────────────────────────────────────────────

    def _astar(
        self,
        start: tuple[int, int],
        goal:  tuple[int, int],
    ) -> list[tuple[int, int]] | None:
        """
        A* on the occupancy grid.

        Args:
            start, goal : (row, col) pixel coordinates
        Returns:
            List of (row, col) from start to goal (inclusive), or None.
        """
        rows, cols = self._grid.shape
        SQRT2 = math.sqrt(2)

        dr_goal = abs(goal[0] - start[0])
        dc_goal = abs(goal[1] - start[1])

        def h(r, c):
            # Octile distance — admissible heuristic for 8-connectivity
            dr, dc = abs(r - goal[0]), abs(c - goal[1])
            return max(dr, dc) + (SQRT2 - 1) * min(dr, dc)

        # 8-directional neighbours: (drow, dcol, cost)
        neighbours = [
            (-1, 0, 1.0), (1, 0, 1.0), (0, -1, 1.0), (0, 1, 1.0),
            (-1, -1, SQRT2), (-1, 1, SQRT2),
            (1,  -1, SQRT2), (1,  1, SQRT2),
        ]

        # g_score stored as a 2D numpy array for O(1) lookup
        INF = float("inf")
        g_score = np.full((rows, cols), INF, dtype=np.float32)
        g_score[start[0], start[1]] = 0.0

        came_from: dict[tuple, tuple] = {}

        # Min-heap: (f_score, row, col)
        open_heap = [(h(*start), start[0], start[1])]

        while open_heap:
            f, r, c = heapq.heappop(open_heap)

            # Stale entry check (g_score is the source of truth)
            g = g_score[r, c]
            if f > g + h(r, c) + 1e-6:
                continue

            if (r, c) == goal:
                # Reconstruct path
                path = [(r, c)]
                node = (r, c)
                while node in came_from:
                    node = came_from[node]
                    path.append(node)
                path.reverse()
                return path

            for dr, dc, cost in neighbours:
                nr, nc = r + dr, c + dc
                if not (0 <= nr < rows and 0 <= nc < cols):
                    continue
                if self._grid[nr, nc]:
                    continue  # obstacle

                ng = g + cost
                if ng < g_score[nr, nc]:
                    g_score[nr, nc] = ng
                    came_from[(nr, nc)] = (r, c)
                    heapq.heappush(open_heap, (ng + h(nr, nc), nr, nc))

        return None  # No path found

    # ── Path smoothing ────────────────────────────────────────────────────────

    def _smooth(self, path: list[tuple[int, int]]) -> list[tuple[int, int]]:
        """
        Remove redundant intermediate waypoints using line-of-sight checks.
        If we can go directly from waypoint A to waypoint C without crossing
        an obstacle, we skip waypoint B.
        """
        if len(path) <= 2:
            return path

        smoothed = [path[0]]
        i = 0
        while i < len(path) - 1:
            # Find the furthest reachable point from path[i]
            j = len(path) - 1
            while j > i + 1:
                if self._line_of_sight(path[i], path[j]):
                    break
                j -= 1
            smoothed.append(path[j])
            i = j

        return smoothed

    def _line_of_sight(
        self, a: tuple[int, int], b: tuple[int, int]
    ) -> bool:
        """
        Bresenham's line algorithm — returns True if no obstacle between a and b.
        """
        r0, c0 = a
        r1, c1 = b
        dr = abs(r1 - r0)
        dc = abs(c1 - c0)
        sr = 1 if r1 > r0 else -1
        sc = 1 if c1 > c0 else -1
        err = dr - dc

        r, c = r0, c0
        while True:
            if self._grid[r, c]:
                return False
            if r == r1 and c == c1:
                break
            e2 = 2 * err
            if e2 > -dc:
                err -= dc
                r += sr
            if e2 < dr:
                err += dr
                c += sc

        return True

    # ── Nearest free cell (fallback) ─────────────────────────────────────────

    def _clamp_to_free(
        self, pixel: tuple[int, int], search_radius: int = 10
    ) -> tuple[int, int] | None:
        """
        If pixel is inside an obstacle (e.g., due to odometry error), find the
        nearest free cell within search_radius pixels. Returns None if not found.
        """
        r, c = pixel
        if not self._grid[r, c]:
            return pixel   # already free

        for radius in range(1, search_radius + 1):
            for dr in range(-radius, radius + 1):
                for dc in range(-radius, radius + 1):
                    nr, nc = r + dr, c + dc
                    if 0 <= nr < self._height and 0 <= nc < self._width:
                        if not self._grid[nr, nc]:
                            return (nr, nc)
        return None


# ── Standalone test ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys

    base = os.path.join(os.path.dirname(__file__), "sim_logs")
    png_path  = os.path.join(base, "map_estimate.png")
    meta_path = os.path.join(base, "map_metadata.json")

    if not os.path.exists(png_path) or not os.path.exists(meta_path):
        print("Run extract_ground_truth.py first to generate sim_logs/")
        sys.exit(1)

    planner = PathPlanner(png_path, meta_path)

    # Test: robot1 start → each victim
    tests = [
        ((-0.375,  0.375), (3.386, -3.042), "robot1 → victim1"),
        ((-0.375,  0.375), (5.290, -3.940), "robot1 → victim2"),
        ((-0.375,  0.375), (2.820,  5.510), "robot1 → victim3"),
        ((-0.375,  0.375), (8.470,  6.540), "robot1 → victim4"),
    ]

    # Draw results on top of the inflated map for visual inspection
    display = Image.open(png_path).convert("RGB")
    pixels  = display.load()
    COLORS  = [(255,0,0), (0,200,0), (0,0,255), (255,140,0)]

    for (sx, sy), (gx, gy), label in tests:
        wps = planner.plan(sx, sy, gx, gy)
        if wps is None:
            print(f"  {label}: NO PATH")
            continue
        print(f"  {label}: {len(wps)} waypoints")

        color = COLORS[tests.index(((sx,sy),(gx,gy),label))]

        # Draw path
        all_pts = [(sx, sy)] + wps
        with open(meta_path) as f:
            meta = json.load(f)
        wmx   = meta["world_min_x"]
        wmy   = meta["world_max_y"]
        res   = meta["resolution"]
        ori_x = meta["origin_x"]
        ori_y = meta["origin_y"]

        def w2p(ox, oy):
            # origin-relative → absolute world → pixel
            wx = ox + ori_x
            wy = oy + ori_y
            return int((wx - wmx) / res), int((wmy - wy) / res)

        prev = w2p(sx, sy)
        for ox, oy in wps:
            cur = w2p(ox, oy)
            # Draw line between prev and cur (simple rasterise)
            x0, y0 = prev
            x1, y1 = cur
            steps = max(abs(x1-x0), abs(y1-y0), 1)
            for i in range(steps + 1):
                px = int(x0 + (x1-x0)*i/steps)
                py = int(y0 + (y1-y0)*i/steps)
                if 0 <= px < display.width and 0 <= py < display.height:
                    for dx in range(-2, 3):
                        for dy in range(-2, 3):
                            ppx, ppy = px+dx, py+dy
                            if 0 <= ppx < display.width and 0 <= ppy < display.height:
                                pixels[ppx, ppy] = color
            prev = cur

        # Mark start (white square) and goal (large square)
        for p, col2 in [(w2p(sx, sy), (255,255,255)), (w2p(gx, gy), color)]:
            for dx in range(-5, 6):
                for dy in range(-5, 6):
                    ppx, ppy = p[0]+dx, p[1]+dy
                    if 0 <= ppx < display.width and 0 <= ppy < display.height:
                        pixels[ppx, ppy] = col2

    out_path = os.path.join(base, "path_debug.png")
    display.save(out_path)
    print(f"\n[OK] Debug image saved → {out_path}")
    print("     Open it to visually verify the paths avoid the walls.")
